# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "UpliftGames/rojo@7.5.1-uplift.syncback.rc.21"
darklua = "seaofvoices/darklua@0.16.0"
asphalt = "jacktabscode/asphalt@0.9.1"
mantle = "blake-mealey/mantle@0.11.18"
syncback-lfs = "Raidflux/rojo-syncback-lfs-locking@0.0.2"
