name: Release Staging

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"
      - "LICENSE.md"
      - "scripts/**"
      - ".github/**"
  release:
    types: [released, prereleased]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: staging_environment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: bun compile

      - name: Build project
        run: bun build

      - name: Upload place artifact
        uses: actions/upload-artifact@v4
        with:
          name: game
          path: game.rbxl

  deploy:
    runs-on: ubuntu-latest
    environment: staging
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: CompeyDev/setup-rokit@v0.1.2

      - name: Download place artifact
        uses: actions/download-artifact@v4
        with:
          name: place

      - name: Deploy game
        run: mantle deploy --allow-purchases --environment staging
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          MANTLE_OPEN_CLOUD_API_KEY: ${{ secrets.MANTLE_OPEN_CLOUD_API_KEY }}